CREATE TABLE FM_UPLOAD_RETURNS_REQUEST 
   (	ID VARCHAR2(100 BYTE), 
	EXTRACTION_ID VARCHAR2(100 BYTE), 
	CREATION_DATE DATE, 
	RETURN_FILE BLOB, 
	USER_ID VARCHAR2(100 BYTE)
   );
 
alter table FM_FLOW_EXPORTING_REQUEST
add REGION_VALIDATION_STATUS VARCHAR2(40);