package it.eng.care.domain.flow.core.enumeration;

public enum MachineEvent {
    ESEGUI_ESTRAZIONE("ESEGUI_ESTRAZIONE"),
    CANCELLA_ESTRAZIONE("CANCELLA_ESTRAZIONE"),
    ESTRAZIONE_FAILED("ESTRAZIONE_FAILED"),
    ESTRAZIONE_SUCCESS("ESTRAZIONE_SUCCESS"),
    ANNULLA_TERMINATA_OK("ANNULLA_TERMINATA_OK"),
    ANNULLA_TERMINATA_KO("ANNULLA_TERMINATA_KO"),
    ESEGUI_EXPORT("ESEGUI_EXPORT"),
    CANCELLA_EXPORT("CANCELLA_EXPORT"),
    EXPORT_FAILED("EXPORT_FAILED"),
    EXPORT_SUCCESS("EXPORT_SUCCESS"),
    ANNULLA_TERMINATA_OK_EXPORT("ANNULLA_TERMINATA_OK_EXPORT"),
    ANNULLA_TERMINATA_KO_EXPORT("ANNULLA_TERMINATA_KO_EXPORT"),
    DRG_TERMINATO_OK("DRG_TERMINATO_OK"),
    DRG_TERMINATO_KO("DRG_TERMINATO_KO"),
    DRG_IN_CORSO("DRG_IN_CORSO"),
    DRG_TERMINATO_KO_FROM_RICHIESTA("DRG_TERMINATO_KO_FROM_RICHIESTA"),
    UPLOAD_COMPLETO("UPLOAD_COMPLETO"),
    UPLOAD_INCOMPLETO("UPLOAD_INCOMPLETO"),
    UPLOAD_RICARICATO_FROM_INCOMPLETO("UPLOAD_RICARICATO_FROM_INCOMPLETO"),
    UPLOAD_WELL_FORMED("UPLOAD_WELL_FORMED"),
    UPLOAD_NOT_WELL_FORMED("UPLOAD_NOT_WELL_FORMED"),
    UPLOAD_RICARICATO_FROM_NOT_WELL_FORMED("UPLOAD_RICARICATO_FROM_NOT_WELL_FORMED"),
    UPLOAD_VALIDATED("UPLOAD_VALIDATED"),
    UPLOAD_NOT_VALIDATED("UPLOAD_NOT_VALIDATED"),
    UPLOAD_RICARICATO_FROM_VALIDATED("UPLOAD_RICARICATO_FROM_VALIDATED")
    ;
    private String event;

    MachineEvent(String event) {
        this.event = event;
    }

    public String getEvent() {
        return event;
    }

}