REM INSERTING into STATE
SET DEFINE OFF;
Insert into STATE (ID,INITIALSTATE,KIND,MACHINEID,REGION,STATE,SUBMACHINEID,INITIALACTION_ID,PARENTSTATE_ID) values (15,0,null,'DRG',null,'IN_CORSO',null,null,null);
Insert into STATE (ID,INITIALSTATE,KIND,MACHINEID,REGION,STATE,SUBMACHINEID,INITIALACTION_ID,PARENTSTATE_ID) values (16,0,null,'DRG',null,'OK',null,null,null);
Insert into STATE (ID,INITIALSTATE,KIND,MACHINEID,REGION,STATE,SUBMACHINEID,INITIALACTION_ID,PARENTSTATE_ID) values (17,0,null,'DRG',null,'KO',null,null,null);
Insert into STATE (ID,INITIALSTATE,KIND,MACHINEID,REGION,STATE,SUBMACHINEID,INITIALACTION_ID,PARENTSTATE_ID) values (25,1,null,'DRG',null,'RICHIESTA',null,null,null);
Insert into STATE (ID,INITIALSTATE,KIND,MACHINEID,REGION,STATE,SUBMACHINEID,INITIALACTION_ID,PARENTSTATE_ID) values (18,1,null,'UPLOAD',null,'LOADED',null,null,null);
Insert into STATE (ID,INITIALSTATE,KIND,MACHINEID,REGION,STATE,SUBMACHINEID,INITIALACTION_ID,PARENTSTATE_ID) values (19,0,null,'UPLOAD',null,'COMPLETE',null,null,null);
Insert into STATE (ID,INITIALSTATE,KIND,MACHINEID,REGION,STATE,SUBMACHINEID,INITIALACTION_ID,PARENTSTATE_ID) values (20,0,null,'UPLOAD',null,'INCOMPLETE',null,null,null);
Insert into STATE (ID,INITIALSTATE,KIND,MACHINEID,REGION,STATE,SUBMACHINEID,INITIALACTION_ID,PARENTSTATE_ID) values (21,0,null,'UPLOAD',null,'WELL_FORMED',null,null,null);
Insert into STATE (ID,INITIALSTATE,KIND,MACHINEID,REGION,STATE,SUBMACHINEID,INITIALACTION_ID,PARENTSTATE_ID) values (22,0,null,'UPLOAD',null,'NOT_WELL_FORMED',null,null,null);
Insert into STATE (ID,INITIALSTATE,KIND,MACHINEID,REGION,STATE,SUBMACHINEID,INITIALACTION_ID,PARENTSTATE_ID) values (23,0,null,'UPLOAD',null,'VALIDATED',null,null,null);
Insert into STATE (ID,INITIALSTATE,KIND,MACHINEID,REGION,STATE,SUBMACHINEID,INITIALACTION_ID,PARENTSTATE_ID) values (24,0,null,'UPLOAD',null,'VALIDATION_ERROR',null,null,null);

REM INSERTING into TRANSITION
SET DEFINE OFF;
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (16,'DRG_TERMINATO_OK',null,'DRG',null,15,16);
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (17,'DRG_TERMINATO_KO',null,'DRG',null,15,17);
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (27,'DRG_IN_CORSO',null,'DRG',null,25,15);
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (18,'UPLOAD_COMPLETO',null,'UPLOAD',null,18,19);
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (19,'UPLOAD_INCOMPLETO',null,'UPLOAD',null,18,20);
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (20,'UPLOAD_RICARICATO_FROM_INCOMPLETO',null,'UPLOAD',null,20,18);
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (21,'UPLOAD_WELL_FORMED',null,'UPLOAD',null,19,21);
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (22,'UPLOAD_NOT_WELL_FORMED',null,'UPLOAD',null,19,22);
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (23,'UPLOAD_RICARICATO_FROM_NOT_WELL_FORMED',null,'UPLOAD',null,22,18);
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (24,'UPLOAD_VALIDATED',null,'UPLOAD',null,21,23);
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (25,'UPLOAD_NOT_VALIDATED',null,'UPLOAD',null,21,24);
Insert into TRANSITION (ID,EVENT,KIND,MACHINEID,GUARD_ID,SOURCE_ID,TARGET_ID) values (26,'UPLOAD_RICARICATO_FROM_VALIDATED',null,'UPLOAD',null,23,18);

COMMIT;
