###DEVELOPE FILE

# HIBERNATE PROPERTIES
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.default_schema=
hibernate.jdbc.batch_size=30
hibernate.cache.use_query_cache=false
hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory
hibernate.cache.use_second_level_cache=false
hibernate.cache.use_structured_entries=false
hibernate.cache.use_minimal_puts=false
hibernate.search.default.directory_provider=filesystem
hibernate.search.default.indexBase=target/lucenefiles
hibernate.search.lucene_version=LUCENE_CURRENT
hibernate.implicit_naming_strategy.applyTo=*
hibernate.hbm2ddl.auto=none
org.hibernate.envers.audit_table_suffix=_A

# DATASOURCE
datasource.url=jdbc:postgresql://161.27.202.52:5432/ellipse_flow_management
datasource.driver=org.postgresql.Driver

### C3P0 
datasource.c3p0.acquire.increment=1
datasource.c3p0.idle.connection.test.period=60
datasource.c3p0.initial.pool.size=1
datasource.c3p0.min.pool.size=1
datasource.c3p0.max.pool.size=3
datasource.c3p0.max.statements=30
datasource.c3p0.debug.unreturned.connection.stack.traces=true
datasource.c3p0.unreturned.connection.timeout=60
