CREATE TABLE FM_FLOW_DRG (
ID VARCHAR2(255) NOT NULL,
EXTRACTION_ID VARCHAR2(255) NOT NULL,
SEND_DATE DATE,
RETURN_DATE DATE,
ERROR VARCHAR2(255),
STATE VARCHAR2(255),
NUM_PRATICHE VARCHAR(255),
CONSTRAINT FK_EXPORT_REQUEST
  FOREIGN KEY (EXTRACTION_ID)
  REFERENCES FM_FLOW_EXPORTING_REQUEST (ID),
  CONSTRAINT PK PRIMARY KEY (ID)
);