insert into fm_tabgen(description, code_desc, field_num, visible, type, ta_id)
values('Tabella di codifica dei risultati del drg',null,4,1,'CONFIGURAZIONI','FM_CODIFICA_RISULTATI_DRG');

INSERT INTO FM_TABGEN_FIELD(TABGEN_ID, DESCRIPTION, PROGRESSIVE, TYPE, VISIBLE, TABGEN_VALUE_COLUMN,TF_ID)
VALUES('FM_CODIFICA_RISULTATI_DRG','FLUSSO',1,'String',1,'FIELD1','FM_CODIFICA_RISULTATI_DRG_FLUSSO');
INSERT INTO FM_TABGEN_FIELD(TABGEN_ID, DESCRIPTION, PROGRESSIVE, TYPE, VISIBLE, TABGEN_VALUE_COLUMN,TF_ID)
VALUES('FM_CODIFICA_RISULTATI_DRG','CAMPO',2,'String',1,'FIELD2','FM_CODIFICA_RISULTATI_DRG_CAMPO');
INSERT INTO FM_TABGEN_FIELD(TABGEN_ID, DESCRIPTION, PROGRESSIVE, TYPE, VISIBLE, TABGEN_VALUE_COLUMN,TF_ID)
VALUES('FM_CODIFICA_RISULTATI_DRG','VALORE_IN',3,'String',1,'FIELD3','FM_CODIFICA_RISULTATI_DRG_VALORE_IN');
INSERT INTO FM_TABGEN_FIELD(TABGEN_ID, DESCRIPTION, PROGRESSIVE, TYPE, VISIBLE, TABGEN_VALUE_COLUMN,TF_ID)
VALUES('FM_CODIFICA_RISULTATI_DRG','VALORE_OUT',4,'String',1,'FIELD4','FM_CODIFICA_RISULTATI_DRG_VALORE_OUT');

INSERT INTO FM_TABGEN_VALUE(TABGEN_ID, FIELD1, FIELD2, FIELD3, FIELD4,TV_ID)
VALUES('FM_CODIFICA_RISULTATI_DRG','SDO','PROGRESSIVOSDO','(?<![^ ])(?=[^ ])','20', (SELECT SYS_GUID() FROM DUAL));

commit;

CREATE OR REPLACE FORCE VIEW FM_CODIFICA_RISULTATI_DRG (FLUSSO, CAMPO, VALORE_IN, VALORE_OUT) AS 
  SELECT FIELD1 AS FLUSSO,
          FIELD2 AS CAMPO,
          FIELD3 AS VALORE_IN,
          FIELD4 AS VALORE_OUT
     FROM FM_TABGEN_VALUE
    WHERE tabgen_id = 'FM_CODIFICA_RISULTATI_DRG';
    
insert into fm_tabgen(description, code_desc, field_num, visible, type, ta_id)
values('Anagrafica dei file restituiti dal servizio di simulazione del ritorno informativo regionale',null,4,1,'CONFIGURAZIONI','FM_FILES_RISULTATI_DRG');

INSERT INTO FM_TABGEN_FIELD(TABGEN_ID, DESCRIPTION, PROGRESSIVE, TYPE, VISIBLE, TABGEN_VALUE_COLUMN,TF_ID)
VALUES('FM_FILES_RISULTATI_DRG','CODICE',1,'String',1,'FIELD1','FM_FILES_RISULTATI_DRG_CODICE');

INSERT INTO FM_TABGEN_FIELD(TABGEN_ID, DESCRIPTION, PROGRESSIVE, TYPE, VISIBLE, TABGEN_VALUE_COLUMN,TF_ID)
VALUES('FM_FILES_RISULTATI_DRG','DESCRIZIONE',2,'String',1,'FIELD2','FM_FILES_RISULTATI_DRG_DESCRIZIONE');


INSERT INTO FM_TABGEN_VALUE(TABGEN_ID, FIELD1, FIELD2, TV_ID)
VALUES('FM_FILES_RISULTATI_DRG','SDO2_01','Scarti', (SELECT SYS_GUID() FROM DUAL));

INSERT INTO FM_TABGEN_VALUE(TABGEN_ID, FIELD1, FIELD2,TV_ID)
VALUES('FM_FILES_RISULTATI_DRG','SDO2_02','Segnalazioni', (SELECT SYS_GUID() FROM DUAL));

INSERT INTO FM_TABGEN_VALUE(TABGEN_ID, FIELD1, FIELD2,TV_ID)
VALUES('FM_FILES_RISULTATI_DRG','SDO2_SIMS_A','Anagrafiche scartate dalla simulazione', (SELECT SYS_GUID() FROM DUAL));

INSERT INTO FM_TABGEN_VALUE(TABGEN_ID, FIELD1, FIELD2,TV_ID)
VALUES('FM_FILES_RISULTATI_DRG','SDO2_SIMS_B','Dati Sanitari scartati dalla simulazione', (SELECT SYS_GUID() FROM DUAL));

INSERT INTO FM_TABGEN_VALUE(TABGEN_ID, FIELD1, FIELD2,TV_ID)
VALUES('FM_FILES_RISULTATI_DRG','SDO2_SIMS_C','Reparti scartati dalla simulazione', (SELECT SYS_GUID() FROM DUAL));

INSERT INTO FM_TABGEN_VALUE(TABGEN_ID, FIELD1, FIELD2,TV_ID)
VALUES('FM_FILES_RISULTATI_DRG','SDO2_SIMS_D','Diagnosi scartate dalla simulazione', (SELECT SYS_GUID() FROM DUAL));

INSERT INTO FM_TABGEN_VALUE(TABGEN_ID, FIELD1, FIELD2,TV_ID)
VALUES('FM_FILES_RISULTATI_DRG','SDO2_SIMS_E','Interventi scartati dalla simulazione', (SELECT SYS_GUID() FROM DUAL));

COMMIT;

CREATE OR REPLACE FORCE VIEW FM_FILES_RISULTATI_DRG (CODICE, DESCRIZIONE) AS 
  SELECT FIELD1 AS CODICE,
          FIELD2 AS DESCRIZIONE
     FROM FM_TABGEN_VALUE
    WHERE tabgen_id = 'FM_FILES_RISULTATI_DRG';
    
REM INSERTING into FM_TABGEN
SET DEFINE OFF;
Insert into FM_TABGEN (DESCRIPTION,CODE_DESC,FIELD_NUM,VISIBLE,TYPE,TA_ID) values ('FM_SDODRG_POS',null,4,1,'CONFIGURAZIONI','FM_SDODRG_POS');

REM INSERTING into FM_TABGEN_FIELD
SET DEFINE OFF;
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('FM_SDODRG_POS','NOMECAMPO',1,'String',null,1,null,1,1,'FIELD1','cab41268-d96c-44c9-a11c-df604wqb6c61');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('FM_SDODRG_POS','LUNGHEZZA',1,'String',null,1,null,1,1,'FIELD2','cab41268-d96c-44c9-a11c-df604plc6c61');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('FM_SDODRG_POS','POSIZIONE',1,'String',null,1,null,1,1,'FIELD3','cab41268-d96c-44c9-a11c-df604asd6c61');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('FM_SDODRG_POS','CAMPOPK',1,'String',null,1,null,1,1,'FIELD4','cab41268-d96c-44c9-a11c-df604xsd6c61');

REM INSERTING into FM_TABGEN_VALUE
SET DEFINE OFF;
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_SDODRG_POS','drg_regionale','3','28','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('13-FEB-20','DD-MON-RR'),'de4c62e2-3038-4788-86b5-c6e04e350749',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_SDODRG_POS','oneredegenza_regionale','1','31','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('13-FEB-20','DD-MON-RR'),'9a45e232-6a7b-476a-821c-b36e2e0cd232',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_SDODRG_POS','codiceazienda','3','1','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('13-FEB-20','DD-MON-RR'),'6f26e473-8217-4aa5-8b2c-59720ebe7919',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_SDODRG_POS','codicepresidio','6','4','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('13-FEB-20','DD-MON-RR'),'1f0d1ab6-bdc4-49aa-a7e3-fa340b87bbdb',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_SDODRG_POS','progressivosdo','8','10','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('13-FEB-20','DD-MON-RR'),'22b19f7b-5429-4313-a7eb-480fe1831786',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_SDODRG_POS','importo_regionale','10','18','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('13-FEB-20','DD-MON-RR'),'51048e5c-478f-4ac8-b832-ebfb34e77059',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

COMMIT;


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "HC40_FLOW_MANAGER"."FM_SDODRG_POS" ("NOMECAMPO", "LUNGHEZZA", "POSIZIONE", "CAMPOPK", "DT_ENABLE", "DT_DISABLE") AS 
  SELECT FIELD1 as NOMECAMPO,
          FIELD2 as LUNGHEZZA,
          FIELD3 as POSIZIONE,
          FIELD4 as CAMPOPK,
          dt_enable,
          dt_disable
     FROM FM_TABGEN_VALUE
    WHERE tabgen_id = 'FM_SDODRG_POS';

COMMIT;