--------------------------------------------------------
--  File created - Friday-November-29-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PS_ER_REG_SCARTI_REGIONE
--------------------------------------------------------

  CREATE TABLE "HC40_FLOW_MANAGER"."PS_ER_REG_SCARTI_REGIONE" 
   (	"TIPOFILE" VARCHAR2(1 BYTE), 
	"CODICEAZIENDA" VARCHAR2(3 BYTE), 
	"CODICESTRUTTURA" VARCHAR2(6 BYTE), 
	"CODICEACCESSOPS" VARCHAR2(8 BYTE), 
	"PROGRESSIVOPRESTAZIONE" VARCHAR2(2 BYTE), 
	"PROGRESSIVODIAGNOSI" VARCHAR2(2 BYTE), 
	"CODICEERRORE" VARCHAR2(4 BYTE), 
	"DESCRIZIONEERRORE" VARCHAR2(200 BYTE), 
	"PROGRESSIVOCAMPO" VARCHAR2(4 BYTE), 
	"DESCRIZIONECAMPO" VARCHAR2(200 BYTE), 
	"VALORECAMPO" VARCHAR2(30 BYTE), 
	"NOTEERRORE" VARCHAR2(200 BYTE), 
	"EXTRACTION_ID" VARCHAR2(256 BYTE), 
	"SEVERITY" VARCHAR2(256 BYTE), 
	"RECEIVING_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
