CREATE TABLE HC40_FLOW_MANAGER.FM_VALIDATION_ERRORS
(
  ID             VARCHAR2(255 BYTE),
  STATUS         VARCHAR2(20 BYTE),
  NUM_RETRY      INTEGER,
  CREATION_DATE  DATE,
  FLOW_ID        VARCHAR2(255 BYTE),
  EXTR_ID        VARCHAR2(255 BYTE),
  ERROR          CLOB,
  DATE_SENT      DATE
)