INSERT INTO FM_TABGEN_VALUE (TABGEN_ID, FIELD1, FIELD2, FIELD3, DT_ENABLE, DT_DISABLE, OPERATION_DATE, TV_ID)
VALUES('FM_CONFIGURATION','upload_file_date_format','Formato delle date contenute nei file dei flussi caricati tramite funzione di upload','[0-9]{4}-[0-9]{2}-[0-9]{2}',SYSDATE, SYSDATE+100, SYSDATE, '1145cb0b-d2c4-47bf-88bc-bcd864f1d75dD');
COMMIT;

INSERT INTO FM_TABGEN_VALUE (TABGEN_ID, FIELD1, FIELD2, FIELD3, DT_ENABLE, DT_DISABLE, OPERATION_DATE, TV_ID)
VALUES('FM_CONFIGURATION','upload_file_date_parser','Parser delle date contenute nei file dei flussi caricati tramite funzione di upload','yyyy-MM-dd"',SYSDATE, SYSDATE+100, SYSDATE, '1145cb0b-d2c4-47bf-88bc-bcd864f1d75dDD');
COMMIT;

alter table fm_Flow_table add required number;

create table FM_SECTION_FILE(
id varchar2(100),
AFILE BLOB,
WELL_FORMED_FILE BLOB,
SECTION_ID varchar2(100)
);


CREATE TABLE FM_FLOW_FILE_UPLOAD_REQUEST
   (	
   ID VARCHAR2(100 BYTE), 
	FLOW_ID VARCHAR2(100 BYTE), 
	VERSION_ID VARCHAR2(100 BYTE), 
	USERNAME VARCHAR2(100 BYTE), 
	CREATION_DATE DATE, 
	VALIDATION_DATE DATE, 
	STATUS VARCHAR2(100 BYTE), 
	 CONSTRAINT FM_FLOW_FILE_UPLOAD_REQUEST_PK PRIMARY KEY (ID), 
	 CONSTRAINT FM_FLOW_FILE_UPLOAD_REQ_FLOW FOREIGN KEY (FLOW_ID)
	  REFERENCES FM_FLOW (ID) ENABLE, 
	 CONSTRAINT FM_FLOW_FILE_UPLOAD_RE_VER FOREIGN KEY (VERSION_ID)
	  REFERENCES FM_VERSION (ID) ENABLE
   );
 
   
    CREATE TABLE FM_FLOW_SECTION_FILE
   (	
   ID VARCHAR2(100), 
	SECTION VARCHAR2(2), 
	UPLOAD_USERNAME VARCHAR2(100), 
	UPLOAD_DATE DATE, 
	REQUEST_ID VARCHAR2(100),
	 CONSTRAINT FM_FLOW_SECTION_FILE_PK PRIMARY KEY (ID), 
	 CONSTRAINT FM_FLOW_SECTION_FILE_REQ FOREIGN KEY (REQUEST_ID)
	  REFERENCES FM_FLOW_FILE_UPLOAD_REQUEST (ID) ENABLE
   );
   
CREATE TABLE FM_FLOW_FILE_UPLOAD_REQ_ERROR
   (	
   ID VARCHAR2(100), 
	ERROR VARCHAR2(1000), 
	REQUEST_ID VARCHAR2(100), 
	SECTION NUMBER,
	INDEX_RECORD NUMBER;
	 CONSTRAINT FM_FILE_UPLOAD_REQ_ERR_PK PRIMARY KEY (ID), 
	 CONSTRAINT FM_FILE_UPLOAD_REQ_ERR_REQ FOREIGN KEY (REQUEST_ID)
	  REFERENCES FM_FLOW_FILE_UPLOAD_REQUEST (ID) ENABLE
   );
