update fm_flow set code = 'SDO' WHERE code = 'SDOIOR';
update fm_flow set name = 'SDO' WHERE name = 'SDOIOR';
update fm_flow set code = 'SDO_REG' WHERE code = 'SDOIOR_REG';
update fm_flow set name = 'SDO_REG' WHERE name = 'SDOIOR_REG';
update fm_flow set code = 'EMUR_PS' WHERE code = 'PS_ER';
update fm_flow set name = 'EMUR_PS' WHERE name = 'PS_ER';
update fm_flow set code = 'EMUR_PS_REG' WHERE code = 'PS_ER_REG';
update fm_flow set name = 'EMUR_PS_REG' WHERE name = 'PS_ER_REG';

UPDATE FM_DASHBOARD SET FLOW = 'EMUR_PS' WHERE FLOW = 'PS_ER';
UPDATE FM_DASHBOARD SET FLOW = 'SDO' WHERE FLOW = 'SDOIOR';

UPDATE FM_DASHBOARD_ERRORS SET FLOW_NAME = 'EMUR_PS' WHERE FLOW_NAME = 'PS_ER';
UPDATE FM_DASHBOARD_ERRORS SET FLOW_NAME = 'SDO' WHERE FLOW_NAME = 'SDOIOR';

UPDATE FM_DASHBOARD_PRATICHE SET FLOW_NAME = 'EMUR_PS' WHERE FLOW_NAME = 'PS_ER';
UPDATE FM_DASHBOARD_PRATICHE SET FLOW_NAME = 'SDO' WHERE FLOW_NAME = 'SDOIOR';

UPDATE FM_TABGEN_VALUE SET FIELD1 = 'SDO' WHERE FIELD1 = 'SDOIOR';
UPDATE FM_TABGEN_VALUE SET FIELD2 = 'SDO' WHERE FIELD2 = 'SDOIOR';
UPDATE FM_TABGEN_VALUE SET FIELD3 = 'SDO' WHERE FIELD3 = 'SDOIOR';
UPDATE FM_TABGEN_VALUE SET FIELD4 = 'SDO' WHERE FIELD4 = 'SDOIOR';
UPDATE FM_TABGEN_VALUE SET FIELD5 = 'SDO' WHERE FIELD5 = 'SDOIOR';
UPDATE FM_TABGEN_VALUE SET FIELD6 = 'SDO' WHERE FIELD6 = 'SDOIOR';
UPDATE FM_TABGEN_VALUE SET FIELD7 = 'SDO' WHERE FIELD7 = 'SDOIOR';
UPDATE FM_TABGEN_VALUE SET FIELD8 = 'SDO' WHERE FIELD8 = 'SDOIOR';
UPDATE FM_TABGEN_VALUE SET FIELD9 = 'SDO' WHERE FIELD9 = 'SDOIOR';
UPDATE FM_TABGEN_VALUE SET FIELD10 = 'SDO' WHERE FIELD10 = 'SDOIOR';
UPDATE FM_TABGEN_VALUE SET FIELD1 = 'EMUR_PS' WHERE FIELD1 = 'PS_ER';
UPDATE FM_TABGEN_VALUE SET FIELD2 = 'EMUR_PS' WHERE FIELD2 = 'PS_ER';
UPDATE FM_TABGEN_VALUE SET FIELD3 = 'EMUR_PS' WHERE FIELD3 = 'PS_ER';
UPDATE FM_TABGEN_VALUE SET FIELD4 = 'EMUR_PS' WHERE FIELD4 = 'PS_ER';
UPDATE FM_TABGEN_VALUE SET FIELD5 = 'EMUR_PS' WHERE FIELD5 = 'PS_ER';
UPDATE FM_TABGEN_VALUE SET FIELD6 = 'EMUR_PS' WHERE FIELD6 = 'PS_ER';
UPDATE FM_TABGEN_VALUE SET FIELD7 = 'EMUR_PS' WHERE FIELD7 = 'PS_ER';
UPDATE FM_TABGEN_VALUE SET FIELD8 = 'EMUR_PS' WHERE FIELD8 = 'PS_ER';
UPDATE FM_TABGEN_VALUE SET FIELD9 = 'EMUR_PS' WHERE FIELD9 = 'PS_ER';
UPDATE FM_TABGEN_VALUE SET FIELD10 = 'EMUR_PS' WHERE FIELD10 = 'PS_ER';

UPDATE FM_TABGEN_VALUE SET FIELD1 = 'SDO_REG' WHERE FIELD1 = 'SDOIOR_REG';
UPDATE FM_TABGEN_VALUE SET FIELD2 = 'SDO_REG' WHERE FIELD2 = 'SDOIOR_REG';
UPDATE FM_TABGEN_VALUE SET FIELD3 = 'SDO_REG' WHERE FIELD3 = 'SDOIOR_REG';
UPDATE FM_TABGEN_VALUE SET FIELD4 = 'SDO_REG' WHERE FIELD4 = 'SDOIOR_REG';
UPDATE FM_TABGEN_VALUE SET FIELD5 = 'SDO_REG' WHERE FIELD5 = 'SDOIOR_REG';
UPDATE FM_TABGEN_VALUE SET FIELD6 = 'SDO_REG' WHERE FIELD6 = 'SDOIOR_REG';
UPDATE FM_TABGEN_VALUE SET FIELD7 = 'SDO_REG' WHERE FIELD7 = 'SDOIOR_REG';
UPDATE FM_TABGEN_VALUE SET FIELD8 = 'SDO_REG' WHERE FIELD8 = 'SDOIOR_REG';
UPDATE FM_TABGEN_VALUE SET FIELD9 = 'SDO_REG' WHERE FIELD9 = 'SDOIOR_REG';
UPDATE FM_TABGEN_VALUE SET FIELD10 = 'SDO_REG' WHERE FIELD10 = 'SDOIOR_REG';
UPDATE FM_TABGEN_VALUE SET FIELD1 = 'EMUR_PS_REG' WHERE FIELD1 = 'PS_ER_REG';
UPDATE FM_TABGEN_VALUE SET FIELD2 = 'EMUR_PS_REG' WHERE FIELD2 = 'PS_ER_REG';
UPDATE FM_TABGEN_VALUE SET FIELD3 = 'EMUR_PS_REG' WHERE FIELD3 = 'PS_ER_REG';
UPDATE FM_TABGEN_VALUE SET FIELD4 = 'EMUR_PS_REG' WHERE FIELD4 = 'PS_ER_REG';
UPDATE FM_TABGEN_VALUE SET FIELD5 = 'EMUR_PS_REG' WHERE FIELD5 = 'PS_ER_REG';
UPDATE FM_TABGEN_VALUE SET FIELD6 = 'EMUR_PS_REG' WHERE FIELD6 = 'PS_ER_REG';
UPDATE FM_TABGEN_VALUE SET FIELD7 = 'EMUR_PS_REG' WHERE FIELD7 = 'PS_ER_REG';
UPDATE FM_TABGEN_VALUE SET FIELD8 = 'EMUR_PS_REG' WHERE FIELD8 = 'PS_ER_REG';
UPDATE FM_TABGEN_VALUE SET FIELD9 = 'EMUR_PS_REG' WHERE FIELD9 = 'PS_ER_REG';
UPDATE FM_TABGEN_VALUE SET FIELD10 = 'EMUR_PS_REG' WHERE FIELD10 = 'PS_ER_REG';

UPDATE FM_VERSION SET VERSION = '1.10' WHERE ID = 'f5115d5e-9a53-4125-bba5-cb133ce7417c';
UPDATE FM_VERSION SET DESCRIPTION = '1.10' WHERE ID = 'f5115d5e-9a53-4125-bba5-cb133ce7417c';
UPDATE FM_VERSION SET VERSION = '1.7' WHERE ID = '0ebc5623-7044-4e5c-91b1-647a4141256d';
UPDATE FM_VERSION SET DESCRIPTION = '1.7' WHERE ID = '0ebc5623-7044-4e5c-91b1-647a4141256d';

update fm_flow_version set version = '0ebc5623-7044-4e5c-91b1-647a4141256d' where flow = '4d971f52-0716-47bc-9255-5e9ca8f0d028';
update fm_flow_version set version = '0ebc5623-7044-4e5c-91b1-647a4141256d' where flow = 'd4bacbce-0e4f-467d-ba9a-4fd0dbae4e22';

update fm_flow_table set version = '0ebc5623-7044-4e5c-91b1-647a4141256d' where flow = '4d971f52-0716-47bc-9255-5e9ca8f0d028';
update fm_flow_table set version = '0ebc5623-7044-4e5c-91b1-647a4141256d' where flow = 'd4bacbce-0e4f-467d-ba9a-4fd0dbae4e22';

RENAME FM_FLOW_SDOIOR_0 TO FM_FLOW_SDO_0;
RENAME FM_FLOW_SDOIOR_REG_0 TO FM_FLOW_SDO_REG_0;
RENAME FM_FLOW_SDOIOR_0_MESSAGE TO FM_FLOW_SDO_0_MESSAGE;
RENAME FM_FLOW_SDOIOR_1 TO FM_FLOW_SDO_1;
RENAME FM_FLOW_SDOIOR_REG_1 TO FM_FLOW_SDO_REG_1;
RENAME FM_FLOW_SDOIOR_1_MESSAGE TO FM_FLOW_SDO_1_MESSAGE;
RENAME FM_FLOW_SDOIOR_2 TO FM_FLOW_SDO_2;
RENAME FM_FLOW_SDOIOR_REG_2 TO FM_FLOW_SDO_REG_2;
RENAME FM_FLOW_SDOIOR_2_MESSAGE TO FM_FLOW_SDO_2_MESSAGE;
RENAME FM_FLOW_SDOIOR_3 TO FM_FLOW_SDO_3;
RENAME FM_FLOW_SDOIOR_REG_3 TO FM_FLOW_SDO_REG_3;
RENAME FM_FLOW_SDOIOR_3_MESSAGE TO FM_FLOW_SDO_3_MESSAGE;
RENAME FM_FLOW_SDOIOR_4 TO FM_FLOW_SDO_4;
RENAME FM_FLOW_SDOIOR_REG_4 TO FM_FLOW_SDO_REG_4;
RENAME FM_FLOW_SDOIOR_4_MESSAGE TO FM_FLOW_SDO_4_MESSAGE;

RENAME FM_FLOW_PS_ER_0 TO FM_FLOW_EMUR_PS_0;
RENAME FM_FLOW_PS_ER_REG_0 TO FM_FLOW_EMUR_PS_REG_0;
RENAME FM_FLOW_PS_ER_0_MESSAGE TO FM_FLOW_EMUR_PS_0_MESSAGE;
RENAME FM_FLOW_PS_ER_1 TO FM_FLOW_EMUR_PS_1;
RENAME FM_FLOW_PS_ER_REG_1 TO FM_FLOW_EMUR_PS_REG_1;
RENAME FM_FLOW_PS_ER_1_MESSAGE TO FM_FLOW_EMUR_PS_1_MESSAGE;
RENAME FM_FLOW_PS_ER_2 TO FM_FLOW_EMUR_PS_2;
RENAME FM_FLOW_PS_ER_REG_2 TO FM_FLOW_EMUR_PS_REG_2;
RENAME FM_FLOW_PS_ER_2_MESSAGE TO FM_FLOW_EMUR_PS_2_MESSAGE;
RENAME FM_FLOW_PS_ER_3 TO FM_FLOW_EMUR_PS_3;
RENAME FM_FLOW_PS_ER_REG_3 TO FM_FLOW_EMUR_PS_REG_3;
RENAME FM_FLOW_PS_ER_3_MESSAGE TO FM_FLOW_EMUR_PS_3_MESSAGE;

UPDATE FM_FLOW_SDO_0 SET VERSION = '1.10';
UPDATE FM_FLOW_SDO_1 SET VERSION = '1.10';
UPDATE FM_FLOW_SDO_2 SET VERSION = '1.10';
UPDATE FM_FLOW_SDO_3 SET VERSION = '1.10';
UPDATE FM_FLOW_SDO_4 SET VERSION = '1.10';
UPDATE FM_FLOW_SDO_REG_0 SET VERSION = '1.10';
UPDATE FM_FLOW_SDO_REG_1 SET VERSION = '1.10';
UPDATE FM_FLOW_SDO_REG_2 SET VERSION = '1.10';
UPDATE FM_FLOW_SDO_REG_3 SET VERSION = '1.10';
UPDATE FM_FLOW_SDO_REG_4 SET VERSION = '1.10';

UPDATE FM_FLOW_EMUR_PS_0 SET VERSION = '1.7';
UPDATE FM_FLOW_EMUR_PS_1 SET VERSION = '1.7';
UPDATE FM_FLOW_EMUR_PS_2 SET VERSION = '1.7';
UPDATE FM_FLOW_EMUR_PS_3 SET VERSION = '1.7';
UPDATE FM_FLOW_EMUR_PS_REG_0 SET VERSION = '1.7';
UPDATE FM_FLOW_EMUR_PS_REG_1 SET VERSION = '1.7';
UPDATE FM_FLOW_EMUR_PS_REG_2 SET VERSION = '1.7';
UPDATE FM_FLOW_EMUR_PS_REG_3 SET VERSION = '1.7';

UPDATE FM_JOB_TALEND SET VERSION = '0ebc5623-7044-4e5c-91b1-647a4141256d' WHERE FLOW = '4d971f52-0716-47bc-9255-5e9ca8f0d028';

update FM_FLOW_CONFIGURATION set version = '0ebc5623-7044-4e5c-91b1-647a4141256d' where flow = '4d971f52-0716-47bc-9255-5e9ca8f0d028';
update FM_FLOW_CONFIGURATION set version = '0ebc5623-7044-4e5c-91b1-647a4141256d' where flow = 'd4bacbce-0e4f-467d-ba9a-4fd0dbae4e22';

UPDATE FM_FLOW_EXPORTING_REQUEST SET VERSION = '0ebc5623-7044-4e5c-91b1-647a4141256d' WHERE FLOW = '4d971f52-0716-47bc-9255-5e9ca8f0d028';

update FM_APP_IDENTITY set flow_name = 'SDO' where flow_name = 'SDOIOR';
update FM_APP_IDENTITY set flow_name = 'EMUR_PS' where flow_name = 'PS_ER';

DELETE FROM FM_TABGEN_VALUE WHERE TABGEN_ID = 'SDOIOR_REG_SCARTI_REGIONE';
DELETE FROM FM_TABGEN_FIELD WHERE TABGEN_ID = 'SDOIOR_REG_SCARTI_REGIONE';
DELETE FROM FM_TABGEN WHERE TA_ID = 'SDOIOR_REG_SCARTI_REGIONE';

Insert into FM_TABGEN (DESCRIPTION,CODE_DESC,FIELD_NUM,VISIBLE,TYPE,TA_ID) values ('Tracciato degli scarti e delle segnalazioni fornite dalla regione',null,3,1,'CONFIGURAZIONI','SDO_REG_SCARTI_REGIONE');

Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('SDO_REG_SCARTI_REGIONE','NOME_CAMPO',1,'String',null,1,null,0,1,'FIELD1','dc00c1dc-1760-4a81-a435-33d0d3f3ee4a');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('SDO_REG_SCARTI_REGIONE','LUNGHEZZA',2,'Integer',null,1,null,0,1,'FIELD2','a92b028f-ff36-4a0b-a9bc-a836e4b09d8e');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('SDO_REG_SCARTI_REGIONE','POSIZIONE',3,'Integer',null,1,null,0,1,'FIELD3','1c5bf434-c3d1-477c-a602-47ff12b3b69b');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('SDO_REG_SCARTI_REGIONE','CAMPO_CHIAVE',4,'String',null,1,null,0,1,'FIELD4','da30c644-c777-49ee-9b7e-2782e159c15a');

Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','VALORECAMPO','30','435','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('22-OCT-19','DD-MON-RR'),'6a107db1-98ee-4946-93d8-e0260a3f8232',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','NOTEERRORE','200','465','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('22-OCT-19','DD-MON-RR'),'0da2ae3f-d0f9-4dbe-9b8a-16e8fe8d1950',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','CODICEAZIENDA','3','2','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('09-MAR-20','DD-MON-RR'),'601ba371-d75b-4f19-8806-2a3d1ed6b3b7',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','CODICEPRESIDIO','6','5','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('09-MAR-20','DD-MON-RR'),'f26be7ad-bd65-47c9-9d43-a150b8d46870',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','TIPOFILE','1','1','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('22-OCT-19','DD-MON-RR'),'2c3bd41a-6f44-483d-b605-7ceac42d6643',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','DESCRIZIONEERRORE','200','31','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('22-OCT-19','DD-MON-RR'),'9be482f5-b7c5-471d-bdba-86ad510d1b4d',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','PROGRESSIVOCAMPO','4','231','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('22-OCT-19','DD-MON-RR'),'4d003f4c-2643-425b-bb37-6b6b86d6a275',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','KPROGRESSIVOSDO','8','11','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('09-MAR-20','DD-MON-RR'),'1ea75c91-88a1-4ea3-a2c6-07ce69814a63',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','PROGRESSIVOREPARTO','2','19','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('25-OCT-19','DD-MON-RR'),'86dd5cab-e031-4667-ab81-a4bb4ee941c5',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','PROGRESSIVODIAGNOSI','2','21','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('22-OCT-19','DD-MON-RR'),'00a25b93-7164-4299-bf51-e776f9c8792a',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','PROGRESSIVOINTERVENTO','2','23','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('22-OCT-19','DD-MON-RR'),'3ee481c7-0d15-4b50-95de-3879660b381a',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','PROGRESSIVOCONTROLLO','2','25','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('22-OCT-19','DD-MON-RR'),'cbfdf2f9-4eef-4dbf-a1c6-aea319658934',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','CODICEERRORE','4','27','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('22-OCT-19','DD-MON-RR'),'1cf8cce2-d241-48c8-ad6e-f8dff8cd6993',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_SCARTI_REGIONE','DESCRIZIONECAMPO','200','235','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('22-OCT-19','DD-MON-RR'),'7eea7d69-0b5a-41f3-b814-42fbe247f587',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);


DELETE FROM FM_TABGEN_VALUE WHERE TABGEN_ID = 'SDOIOR_REG_CORREZIONI_REGIONE';
DELETE FROM FM_TABGEN_FIELD WHERE TABGEN_ID = 'SDOIOR_REG_CORREZIONI_REGIONE';
DELETE FROM FM_TABGEN WHERE TA_ID = 'SDOIOR_REG_CORREZIONI_REGIONE';

Insert into FM_TABGEN (DESCRIPTION,CODE_DESC,FIELD_NUM,VISIBLE,TYPE,TA_ID) values ('Tracciato del file degli importi e drg inviato dalla regione',null,4,1,'CONFIGURAZIONI','SDO_REG_CORREZIONI_REGIONE');

Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('SDO_REG_CORREZIONI_REGIONE','NOME_CAMPO',1,'String',null,1,null,0,1,'FIELD1','c9f369f3-b4fb-4eb5-94fd-ed314a676297');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('SDO_REG_CORREZIONI_REGIONE','LUNGHEZZA',2,'Integer',null,1,null,0,1,'FIELD2','91d0a928-b032-49a3-a018-694d508e8da5');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('SDO_REG_CORREZIONI_REGIONE','POSIZIONE',3,'Integer',null,1,null,0,1,'FIELD3','25b1bb8e-590d-4b60-9ff1-3ada326ca3f6');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('SDO_REG_CORREZIONI_REGIONE','CAMPO_CONTROLLO',4,'Integer',null,1,null,0,1,'FIELD4','1ab1642d-75d4-4cb2-a270-a805e0647c1e');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('SDO_REG_CORREZIONI_REGIONE','CAMPO_CHIAVE',5,'String',null,1,null,0,1,'FIELD5','2d612940-d31a-45f3-bfea-865732e4840a');

Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_CORREZIONI_REGIONE','CODICEAZIENDA','3','1','0','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-MAR-20','DD-MON-RR'),'97a4acac-1541-40b6-8be3-57f98c07c89a',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_CORREZIONI_REGIONE','CODICEPRESIDIO','6','4','0','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-MAR-20','DD-MON-RR'),'afc97b45-98b9-470c-b0d3-71fe76768931',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_CORREZIONI_REGIONE','KPROGRESSIVOSDO','8','10','0','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-MAR-20','DD-MON-RR'),'5bc5251e-a421-4ead-b8de-417a6285df4a',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_CORREZIONI_REGIONE','IMPORTO_REGIONALE','10','18','0','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-MAR-20','DD-MON-RR'),'54fe4748-9af7-407a-98d5-87354c0a43fe',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_CORREZIONI_REGIONE','DRG_REGIONALE','3','28','0','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-MAR-20','DD-MON-RR'),'9126f62b-3a10-4046-a2f8-4e1749a0e7b1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_CORREZIONI_REGIONE','ONEREDEGENZA_REGIONALE','1','31','0','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-MAR-20','DD-MON-RR'),'b9bb07be-77e5-44c9-8672-1ceae6100b51',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('SDO_REG_CORREZIONI_REGIONE','TIPORECORD','1','32','1','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-MAR-20','DD-MON-RR'),'3a98b245-2e6c-42b7-bd6a-68dfbca1c89f',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

RENAME PS_ER_REG_SCARTI_REGIONE TO EMUR_PS_REG_SCARTI_REGIONE;
RENAME SDOIOR_REG_SCARTI_REGIONE TO SDO_REG_SCARTI_REGIONE;

update fm_flow_rule set version = '0ebc5623-7044-4e5c-91b1-647a4141256d' where flow = '4d971f52-0716-47bc-9255-5e9ca8f0d028';

DELETE FROM FM_TABGEN_VALUE WHERE TABGEN_ID = 'PS_ER_REG_SCARTI_REGIONE';
DELETE FROM FM_TABGEN_FIELD WHERE TABGEN_ID = 'PS_ER_REG_SCARTI_REGIONE';
DELETE FROM FM_TABGEN WHERE TA_ID = 'PS_ER_REG_SCARTI_REGIONE';

Insert into FM_TABGEN (DESCRIPTION,CODE_DESC,FIELD_NUM,VISIBLE,TYPE,TA_ID) values ('Tracciato per ps ',null,4,1,'CONFIGURAZIONI','EMUR_PS_REG_SCARTI_REGIONE');

Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('EMUR_PS_REG_SCARTI_REGIONE','NOME_CAMPO',1,'String',null,1,null,0,1,'FIELD1','bac46077-086c-458c-adff-2e32b939e76c');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('EMUR_PS_REG_SCARTI_REGIONE','LUNGHEZZA',2,'Integer',null,1,null,0,1,'FIELD2','41a93873-907b-48f0-90e2-f09866c3f1bc');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('EMUR_PS_REG_SCARTI_REGIONE','POSIZIONE',3,'Integer',null,1,null,0,1,'FIELD3','97fc459a-93cd-4bbe-bb87-f6816af4895c');
Insert into FM_TABGEN_FIELD (TABGEN_ID,DESCRIPTION,PROGRESSIVE,TYPE,FORMAT,VISIBLE,TABGEN_FIELD_ID,PK,NULLABLE,TABGEN_VALUE_COLUMN,TF_ID) values ('EMUR_PS_REG_SCARTI_REGIONE','CAMPO_CHIAVE',4,'String',null,1,null,0,1,'FIELD4','a01c5e01-591c-4b9f-9574-2d3caea699a4');

Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('EMUR_PS_REG_SCARTI_REGIONE','TIPOFILE','1','1','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('09-MAR-20','DD-MON-RR'),'428aa0d3-9095-4ca8-a834-c8a3096fee00',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('EMUR_PS_REG_SCARTI_REGIONE','CODICESTRUTTURA','8','5','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('09-MAR-20','DD-MON-RR'),'e9c3a95e-7b6f-4cc0-9212-94511f23af62',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('EMUR_PS_REG_SCARTI_REGIONE','KCODICEACCESSOPS','15','13','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('09-MAR-20','DD-MON-RR'),'027484f9-8eb9-466f-b109-a56b836b1cc3',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('EMUR_PS_REG_SCARTI_REGIONE','CODICEERRORE','4','28','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('09-MAR-20','DD-MON-RR'),'93f53017-2723-4cd5-afe7-22820ce87bed',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('EMUR_PS_REG_SCARTI_REGIONE','PROGRESSIVOCAMPO','3','92','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('09-MAR-20','DD-MON-RR'),'f2f30eba-ad03-425b-a910-25506a7e9e3d',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('EMUR_PS_REG_SCARTI_REGIONE','CODICEAZIENDA','3','2','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('09-MAR-20','DD-MON-RR'),'5616eafa-b09d-402f-bb89-fdf138106a31',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('EMUR_PS_REG_SCARTI_REGIONE','DESCRIZIONEERRORE','60','32','0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('09-MAR-20','DD-MON-RR'),'8245b106-1848-43c4-8f60-ea9935612477',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);


delete from fm_tabgen_value where tabgen_id = 'FM_DASHBOARD_CONFIG';

Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0001','c299ad8c-012e-471c-8c0c-ac721fe242cf','ANAGRAFICHE_ERRATE','SELECT    mese,    anno,    nvl(cc, 0)FROM    dashboardmeseanno left    JOIN (        SELECT            month_rif,            year_rif,            COUNT(1) cc        FROM            fm_flow_sdo_0        WHERE            status = ''ERROR''  and month_rif in (:mesi)            and year_rif in (:anni)        GROUP BY            month_rif,            year_rif    ) ON mese = month_rif         AND anno = year_rif         where mese in (:mesi)            and anno in (:anni)','Anagrafiche Errate',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'d7fc674a-67b7-4654-ae89-39a100661b1c',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0010','c299ad8c-012e-471c-8c0c-ac721fe242cf','PRATICHE_ERRATE_REG','SELECT     z.mese,     z.anno,     (         SELECT             nvl(COUNT(1), 0)         FROM             fm_flow_sdo_0 b         WHERE             b.status_region = ''SCARTO''             AND b.month_rif = to_number(z.mese)             AND b.year_rif = to_number(z.anno)             AND b.state_send_region = ''ACCETTATA''             AND b.month_rif IN (                 :mesi             )             AND b.year_rif IN (                 :anni             )     ) FROM     dashboardmeseanno z WHERE     z.mese IN (         :mesi     )     AND z.anno IN (         :anni     )','Pratiche Errate Da Regione','card-header-warning','warning','Visualizza pratiche errate da regione','TRUE','REGIONALE','PRATICHE_ERR',null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'99',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0025','c299ad8c-012e-471c-8c0c-ac721fe242cf','RICAVI_TOT_RIC_REG','SELECT
    z.mese,
    z.anno,
    (
        SELECT
            nvl(SUM(to_number(replace(regexp_replace(nvl(importoaziendale, ''0''), ''0[0*]0,[0*]0'', ''0''), '','', ''.''))), 0) v
        FROM
            fm_flow_sdo_1 p
            JOIN fm_flow_sdo_0 q ON p.codiceazienda = q.codiceazienda
                                       AND p.progressivosdo = q.progressivosdo
                                       AND p.codicepresidio = q.codicepresidio
        WHERE
            q.month_rif = to_number(z.mese)
            AND q.year_rif = to_number(z.anno)
            AND q.state_send_region = ''ACCETTATA''
            AND q.status_region = ''VALIDO''
            and q.month_rif in (:mesi)
and q.year_rif in (:anni)
    ) tot
FROM
    dashboardmeseanno z
    where z.mese in (:mesi)
and z.anno in (:anni)
ORDER BY
    z.mese,
    z.anno','Ricavi Totali Riconosciute Da Regione','card-header-primary','attach_money','Ricavi totali regionali','TRUE','REGIONALE',null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'bdf2d465-3add-4fb6-91c4-0d36ad83e346',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0014','4d971f52-0716-47bc-9255-5e9ca8f0d028','PRATICHE','SELECT
    mese,
    anno,
    nvl(c, 0)
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(1) c,
            month_rif,
            year_rif
        FROM
            fm_flow_emur_ps_0
        WHERE
            month_rif IS NOT NULL
            AND year_rif IS NOT NULL
            and month_rif in (:mesi)
and year_rif in (:anni)
        GROUP BY
            month_rif,
            year_rif
    ) a ON mese = month_rif
           AND anno = year_rif
           where mese in (:mesi)
and anno in (:anni)
ORDER BY
    to_number(anno),
    to_number(mese)','Pratiche',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,null,'ce64e004-eba2-46d1-98bf-384b208ad0c9',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0027','4d971f52-0716-47bc-9255-5e9ca8f0d028','PRATICHE_NOT_SEND_REG','SELECT
    mese,
    anno,
    nvl(c, 0)
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(1) c,
            month_rif,
            year_rif
        FROM
            fm_flow_emur_ps_0
        WHERE
            month_rif IS NOT NULL
            AND year_rif IS NOT NULL
            AND ( state_send_region = ''DA_INVIARE''
                  AND month_rif IN (
                :mesi
            )
                  AND year_rif IN (
                :anni
            ) )
        GROUP BY
            month_rif,
            year_rif
    ) a ON mese = month_rif
           AND anno = year_rif
WHERE
    mese IN (
        :mesi
    )
    AND anno IN (
        :anni
    )
ORDER BY
    to_number(anno),
    to_number(mese)','Pratiche ancora non inviate a regione','card-header-rose','event_note','Visualizza pratiche ancora non inviate a regione','TRUE','REGIONALE','PRATICHE',null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'46aba0bc-dcdb-496f-bfce-6c44036916a2',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0019','4d971f52-0716-47bc-9255-5e9ca8f0d028','ANAGRAFICHE_ERRATE','SELECT    mese,    anno,    nvl(cc, 0)FROM    dashboardmeseanno left    JOIN (        SELECT            month_rif,            year_rif,            COUNT(1) cc        FROM            fm_flow_emur_ps_0        WHERE            status = ''ERROR''        and month_rif in (:mesi)and year_rif in (:anni)        GROUP BY            month_rif,            year_rif    ) ON mese = month_rif         AND anno = year_rif         where mese in (:mesi)and anno in (:anni)','Anagrafiche Errate',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'a00d0be3-9f97-432e-b082-609a961dcf87',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0011','4d971f52-0716-47bc-9255-5e9ca8f0d028','SCARTO_ANAGRAFICHE','SELECT     z.mese,     z.anno,     (         SELECT             nvl(SUM(to_number(replace(regexp_replace(nvl(importolordo, ''0''), ''0[0*]0,[0*]0'', ''0''), '','', ''.''))), 0)         FROM             fm_flow_emur_ps_0 p             JOIN fm_flow_emur_ps_1 q ON p.codiceazienda = q.codiceazienda                                       AND p.codicestruttura = q.codicestruttura                                       AND p.codiceaccessops = q.codiceaccessops         WHERE             p.status = ''ERROR''             AND p.month_rif = to_number(z.mese)             AND p.year_rif = to_number(z.anno)             AND p.month_rif IN (                 :mesi             )             AND p.year_rif IN (                 :anni             )     ) tot from dashboardmeseanno z WHERE z.mese IN (     :mesi ) AND z.anno IN (     :anni )','Scarto Anagrafiche',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'2d49e18c-607b-464c-b8a9-28dbda54853a',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0028','c299ad8c-012e-471c-8c0c-ac721fe242cf','PRATICHE_NOT_SEND_REG','SELECT
    mese,
    anno,
    nvl(c, 0)
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(1) c,
            month_rif,
            year_rif
        FROM
            fm_flow_sdo_0
        WHERE
            month_rif IS NOT NULL
            AND year_rif IS NOT NULL
            AND ( state_send_region = ''DA_INVIARE''
                  AND month_rif IN (
                :mesi
            )
                  AND year_rif IN (
                :anni
            ) )
        GROUP BY
            month_rif,
            year_rif
    ) a ON mese = month_rif
           AND anno = year_rif
WHERE
    mese IN (
        :mesi
    )
    AND anno IN (
        :anni
    )
ORDER BY
    to_number(anno),
    to_number(mese)','Pratiche ancora non inviate a regione','card-header-rose','event_note','Visualizza pratiche ancora non inviate a regione','TRUE','REGIONALE','PRATICHE',null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'ffc907d0-e4aa-44ac-ae0e-a92a30b4a7fb',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0020','c299ad8c-012e-471c-8c0c-ac721fe242cf','PRATICHE_REG','SELECT
    mese,
    anno,
    nvl(c, 0)
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(1) c,
            month_rif,
            year_rif
        FROM
            fm_flow_sdo_0
        WHERE
            month_rif IS NOT NULL
            AND year_rif IS NOT NULL
            AND (state_send_region = ''INVIATA''
            OR state_send_region = ''ACCETTATA'')
            and month_rif in (:mesi)
and year_rif in (:anni)
        GROUP BY
            month_rif,
            year_rif
    ) a ON mese = month_rif
           AND anno = year_rif
           where mese in (:mesi)
and anno in (:anni)
ORDER BY
    to_number(anno),
    to_number(mese)','Pratiche Inviate a Regione','card-header-info','arrow_forward_ios','Visualizza pratiche inviate a regione','TRUE','REGIONALE','PRATICHE',null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'cab05b54-a46f-4da6-b4af-3cde7aa0d2a0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0022','4d971f52-0716-47bc-9255-5e9ca8f0d028','PRATICHE_ERRATE_REG','SELECT     z.mese,     z.anno,     (         SELECT             nvl(COUNT(1), 0)         FROM             fm_flow_emur_ps_0 b         WHERE             b.status_region = ''SCARTO''             AND b.month_rif = to_number(z.mese)             AND b.year_rif = to_number(z.anno)             AND b.month_rif IN (                 :mesi             )             AND b.year_rif IN (                 :anni             )     ) FROM     dashboardmeseanno z WHERE     z.mese IN (         :mesi     )     AND z.anno IN (         :anni     )','Pratiche Errate Da Regione','card-header-warning','warning','Visualizza pratiche errate da regione','TRUE','REGIONALE','PRATICHE_ERR',null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'5c92cb85-9e23-4048-92e6-b45661618e6a',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0029','c299ad8c-012e-471c-8c0c-ac721fe242cf','ERRORI_REG','SELECT
    mese,
    anno,
    nvl(c, 0)
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(1) c,
            month_rif,
            year_rif
        FROM
            fm_flow_sdo_0
            JOIN sdo_reg_scarti_regione ON sdo_reg_scarti_regione.codiceazienda = fm_flow_sdo_0.codiceazienda
                                             AND sdo_reg_scarti_regione.codicepresidio = fm_flow_sdo_0.codicepresidio
                                             AND
                                             fm_flow_sdo_0.progressivosdo in (
                                                  select progressivosdo
                                                  from fm_flow_sdo_reg_0 reg where
                                                    reg.kprogressivosdo = sdo_reg_scarti_regione.kprogressivosdo and
                                                    reg.CODICEAZIENDA = sdo_reg_scarti_regione.CODICEAZIENDA and
                                                    reg.CODICEPRESIDIO = sdo_reg_scarti_regione.CODICEPRESIDIO)
        WHERE
            month_rif IS NOT NULL
            AND year_rif IS NOT NULL
            AND month_rif IN (
                :mesi
            )
            AND year_rif IN (
                :anni
            )
        GROUP BY
            month_rif,
            year_rif
    ) a ON mese = month_rif
           AND anno = year_rif
WHERE
    mese IN (
        :mesi
    )
    AND anno IN (
        :anni
    )
ORDER BY
    to_number(anno),
    to_number(mese)','Errori Regionali','card-header-danger','error','Visualizza errori regionali','TRUE','REGIONALE','ERRORI',null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'f609f102-551d-471a-ba9d-7d50ccd5ca42',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0002','c299ad8c-012e-471c-8c0c-ac721fe242cf','SCARTO_ANAGRAFICHE','SELECT     z.mese,     z.anno,     (         SELECT             nvl(SUM(to_number(replace(regexp_replace(nvl(importoaziendale, ''0''), ''0[0*]0,[0*]0'', ''0''), '','', ''.''))), ''0'')         FROM             fm_flow_sdo_0 p             JOIN fm_flow_sdo_1 q ON p.codiceazienda = q.codiceazienda                                        AND p.codicepresidio = q.codicepresidio                                        AND p.progressivosdo = q.progressivosdo         WHERE             p.status = ''ERROR''             AND p.month_rif = to_number(z.mese)             AND p.year_rif = to_number(z.anno)             AND p.month_rif IN (                 :mesi             )             AND p.year_rif IN (                 :anni             )     ) tot from dashboardmeseanno z where z.mese in (:mesi) and z.anno in ( :anni )','Scarto Anagrafiche',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'2b6bdfb9-b97f-4e8a-850b-a31c1896eeac',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0026','4d971f52-0716-47bc-9255-5e9ca8f0d028','RICAVI_TOT_RIC_REG','SELECT
    z.mese,
    z.anno,
    (
        SELECT
            nvl(SUM(to_number(replace(regexp_replace(nvl(importolordo, ''0''), ''0[0*]0,[0*]0'', ''0''), '','', ''.''))), 0) v
        FROM
            fm_flow_emur_ps_1 p
            JOIN fm_flow_emur_ps_0 q ON p.codiceazienda = q.codiceazienda
                                       AND p.codicestruttura = q.codicestruttura
                                       AND p.codiceaccessops = q.codiceaccessops
        WHERE
            q.month_rif = to_number(z.mese)
            AND q.year_rif = to_number(z.anno)
            AND q.state_send_region = ''ACCETTATA''
            AND q.status_region = ''VALIDO''
            and q.month_rif in (:mesi)
and q.year_rif in (:anni)
    ) tot
FROM
    dashboardmeseanno z
    where z.mese in (:mesi)
and z.anno in (:anni)
ORDER BY
    z.mese,
    z.anno','Ricavi Totali Riconosciute Da Regione','card-header-primary','attach_money','Ricavi totali regionali','TRUE','REGIONALE',null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'ef91f446-60b5-4fb4-a365-32659f4a0627',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0013','4d971f52-0716-47bc-9255-5e9ca8f0d028','PRATICHE_ERRATE','SELECT    z.mese,    z.anno,    (        SELECT            nvl(COUNT(1), 0)        FROM            fm_flow_emur_ps_0 b        WHERE            b.status_group = ''ERROR''            AND b.month_rif = to_number(z.mese)            AND b.year_rif = to_number(z.anno)            and b.month_rif in (:mesi)and b.year_rif in (:anni)    )FROM    dashboardmeseanno z    where z.mese in (:mesi)and z.anno in (:anni)','Pratiche Errate',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'f9643af9-233f-4fdf-a455-63b685e1d266',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0023','4d971f52-0716-47bc-9255-5e9ca8f0d028','PRATICHE_REG','SELECT
    mese,
    anno,
    nvl(c, 0)
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(1) c,
            month_rif,
            year_rif
        FROM
            fm_flow_emur_ps_0
        WHERE
            month_rif IS NOT NULL
            AND year_rif IS NOT NULL
            AND (state_send_region = ''INVIATA''
            OR state_send_region = ''ACCETTATA''
            and month_rif in (:mesi)
and year_rif in (:anni)
)
        GROUP BY
            month_rif,
            year_rif
    ) a ON mese = month_rif
           AND anno = year_rif
           where mese in (:mesi)
and anno in (:anni)
ORDER BY
    to_number(anno),
    to_number(mese)','Pratiche Inviate a Regione','card-header-info','arrow_forward_ios','Visualizza pratiche inviate a regione','TRUE','REGIONALE','PRATICHE',null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'25eb6b9a-5358-428b-9839-7bd6639f06d8',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0024','4d971f52-0716-47bc-9255-5e9ca8f0d028','PRATICHE_RIC_REG','SELECT
    mese,
    anno,
    nvl(c, 0)
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(1) c,
            month_rif,
            year_rif
        FROM
            fm_flow_emur_ps_0
        WHERE
            month_rif IS NOT NULL
            AND year_rif IS NOT NULL
            AND state_send_region = ''ACCETTATA''
            AND status_region = ''VALIDO''
            and month_rif in (:mesi)
and year_rif in (:anni)
        GROUP BY
            month_rif,
            year_rif
    ) a ON mese = month_rif
           AND anno = year_rif
           where mese in (:mesi)
and anno in (:anni)
ORDER BY
    to_number(anno),
    to_number(mese)','Pratiche Riconosciute da Regione','card-header-success','grade','Visualizza pratiche riconosciute da regione','TRUE','REGIONALE','PRATICHE',null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'486938bc-a7f6-4648-ba3d-a91d52277de0',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0017','4d971f52-0716-47bc-9255-5e9ca8f0d028','RICAVI_TOTALI','SELECT
    z.mese,
    z.anno,
    (
        SELECT
            nvl(SUM(to_number(replace(regexp_replace(nvl(importolordo, ''0''), ''0[0*]0,[0*]0'', ''0''), '','', ''.''))), ''0'') v
        FROM
            fm_flow_emur_ps_1 p
        WHERE
            p.status_group = ''VALID''
            AND p.month_rif = to_number(z.mese)
            AND p.year_rif = to_number(z.anno)
            AND p.month_rif IN (
                :mesi
            )
            AND p.year_rif IN (
                :anni
            )
    ) tot
FROM
    dashboardmeseanno z
WHERE
    z.mese IN (
        :mesi
    )
    AND z.anno IN (
        :anni
    )','Ricavi Totali','card-header-primary','attach_money','Ricavi totali','TRUE','AZIENDALE',null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'059f8384-da24-46ee-a083-b98b249d1e97',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0018','4d971f52-0716-47bc-9255-5e9ca8f0d028','DATI_CLINICI_ERRATI','SELECT    z.mese,    z.anno,    nvl(v, 0)FROM    dashboardmeseanno z    LEFT JOIN (        SELECT            p.month_rif,            p.year_rif,            COUNT(1) v        FROM            fm_flow_emur_ps_1 p            LEFT JOIN fm_flow_emur_ps_2 q ON p.codiceazienda = q.codiceazienda                                           AND p.codicestruttura = q.codicestruttura                                           AND p.codiceaccessops = q.codiceaccessops                                           AND p.status = q.status            LEFT JOIN fm_flow_emur_ps_3 w ON p.codiceazienda = w.codiceazienda                                           AND p.codicestruttura = w.codicestruttura                                           AND p.codiceaccessops = w.codiceaccessops                                           AND p.status = w.status        WHERE            p.status =  ''ERROR''            and p.month_rif in (:mesi)and p.year_rif in (:anni)        GROUP BY            p.month_rif,            p.year_rif    ) c ON z.mese = month_rif           AND z.anno = year_rif           where z.mese in (:mesi)and z.anno in (:anni)ORDER BY    to_number(z.anno),    to_number(z.mese)','Dati Clinici Errati',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'a6fdbf72-2d53-4dcd-bdd4-32b1c94586f8',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0012','4d971f52-0716-47bc-9255-5e9ca8f0d028','SCARTO_DATI_CLINICI','SELECT     mese,     anno,     nvl(v, 0) FROM     dashboardmeseanno left     JOIN (         SELECT             month_rif,             year_rif,             SUM(to_number(replace(regexp_replace(nvl(importolordo, ''0''), ''0[0*]0,[0*]0'', ''0''), '','', ''.''))) v         FROM             fm_flow_emur_ps_1 p         WHERE             status = ''ERROR''             AND month_rif IN (                 :mesi             )             AND year_rif IN (                 :anni             )             OR EXISTS (                 SELECT                     1                 FROM                     fm_flow_emur_ps_2 q                 WHERE                     p.codiceazienda = q.codiceazienda                     AND p.codicestruttura = q.codicestruttura                     AND p.codiceaccessops = q.codiceaccessops                     AND q.status = ''ERROR''                     AND q.month_rif IN (                         :mesi                     )                     AND q.year_rif IN (                         :anni                     )             )             OR EXISTS (                 SELECT                     1                 FROM                     fm_flow_emur_ps_3 q                 WHERE                     p.codiceazienda = q.codiceazienda                     AND p.codicestruttura = q.codicestruttura                     AND p.codiceaccessops = q.codiceaccessops                     AND q.status = ''ERROR''                     AND q.month_rif IN (                         :mesi                     )                     AND q.year_rif IN (                         :anni                     )             )         GROUP BY             month_rif,             year_rif     ) ON mese = month_rif          AND anno = year_rif where mese IN (     :mesi ) AND anno IN (     :anni )ORDER BY to_number(anno), to_number(mese)','Scarto Dati Clinici',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'f3230d2d-4646-4b4e-a833-2cb47c7929c1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0006','c299ad8c-012e-471c-8c0c-ac721fe242cf','PRATICHE_ERRATE','SELECT     z.mese,     z.anno,     (         SELECT             nvl(COUNT(1), 0)         FROM             fm_flow_sdo_0 b         WHERE             b.status_group = ''ERROR''             AND b.month_rif = to_number(z.mese)             AND b.year_rif = to_number(z.anno)             AND b.month_rif IN (                 :mesi             )             AND b.year_rif IN (                 :anni             )     ) FROM     dashboardmeseanno z where z.mese IN (     :mesi ) AND z.anno IN (     :anni )','Pratiche Errate',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'dd699322-75ed-4b37-96a3-669a27bdb9c2',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0003','c299ad8c-012e-471c-8c0c-ac721fe242cf','SCARTO_DATI_CLINICI','SELECT    mese,    anno,    nvl(v, 0)FROM    dashboardmeseanno left    JOIN (        SELECT            month_rif,            year_rif,            SUM(to_number(replace(regexp_replace(nvl(importoaziendale, ''0''), ''0[0*]0,[0*]0'', ''0''), '','', ''.''))) v        FROM            fm_flow_sdo_1 p        WHERE            status  = ''ERROR''   and month_rif in (:mesi)            and year_rif in (:anni)            OR EXISTS (                SELECT                    1                FROM                    fm_flow_sdo_2 q                WHERE                    p.codiceazienda = q.codiceazienda                    AND p.codicepresidio = q.codicepresidio                    AND p.progressivosdo = q.progressivosdo                    AND q.status  = ''ERROR''and q.month_rif in (:mesi)            and q.year_rif in (:anni)            )            OR EXISTS (                SELECT                    1                FROM                    fm_flow_sdo_3 q                WHERE                    p.codiceazienda = q.codiceazienda                    AND p.codicepresidio = q.codicepresidio                    AND p.progressivosdo = q.progressivosdo                    AND q.status  = ''ERROR''and q.month_rif in (:mesi)            and q.year_rif in (:anni)            )            OR EXISTS (                SELECT                    1                FROM                    fm_flow_sdo_4 q                WHERE                    p.codiceazienda = q.codiceazienda                    AND p.codicepresidio = q.codicepresidio                    AND p.progressivosdo = q.progressivosdo                    AND q.status  = ''ERROR''and q.month_rif in (:mesi)            and q.year_rif in (:anni)            )        GROUP BY            month_rif,            year_rif    ) ON mese = month_rif         AND anno = year_rif         where mese in (:mesi)         and anno in (:anni)ORDER BY    to_number(anno),    to_number(mese)','Scarto Dati Clinici',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'34e198d0-f7bb-4fca-ba35-3daf74e54a5f',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0004','c299ad8c-012e-471c-8c0c-ac721fe242cf','RICAVI_TOTALI','SELECT
    z.mese,
    z.anno,
    (
        SELECT
            nvl(SUM(to_number(replace(regexp_replace(nvl(IMPORTOAZIENDALE, ''0''), ''0[0*]0,[0*]0'', ''0''), '','', ''.''))), 0) v
        FROM
            fm_flow_sdo_1 p
        WHERE
            p.status_group = ''VALID''
            AND p.month_rif = to_number(z.mese)
            AND p.year_rif = to_number(z.anno)
            and p.month_rif in (:mesi)
            and p.year_rif in (:anni)
    ) tot
FROM
    dashboardmeseanno z
    where z.mese in (:mesi)
    and z.anno in (:anni)','Ricavi Totali','card-header-primary','attach_money','Ricavi totali','TRUE','AZIENDALE',null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'9d5f4ea9-bef5-45b0-923f-71aa48af0f3b',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0005','c299ad8c-012e-471c-8c0c-ac721fe242cf','DATI_CLINICI_ERRATI','SELECT    z.mese,    z.anno,    nvl(v, 0)FROM    dashboardmeseanno z    LEFT JOIN (        SELECT            p.month_rif,            p.year_rif,            COUNT(1) v        FROM            fm_flow_sdo_1 p            LEFT JOIN fm_flow_sdo_2 q ON p.codiceazienda = q.codiceazienda                                            AND p.codicepresidio = q.codicepresidio                                            AND p.progressivosdo = q.progressivosdo                                            AND p.status = q.status            LEFT JOIN fm_flow_sdo_3 w ON p.codiceazienda = w.codiceazienda                                            AND p.codicepresidio = w.codicepresidio                                            AND p.progressivosdo = w.progressivosdo                                            AND p.status = w.status            LEFT JOIN fm_flow_sdo_4 t ON p.codiceazienda = t.codiceazienda                                            AND p.codicepresidio = t.codicepresidio                                            AND p.progressivosdo = t.progressivosdo                                            AND p.status = t.status        WHERE            p.status=   ''ERROR''          and p.month_rif in (:mesi)            and p.year_rif in (:anni)        GROUP BY            p.month_rif,            p.year_rif    ) c ON z.mese = month_rif           AND z.anno = year_rif           where z.mese in (:mesi)           and z.anno in (:anni)ORDER BY    to_number(z.anno),    to_number(z.mese)','Dati Clinici Errati',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'7fcb36e5-e78c-4dcc-81e0-674c20fdc9d6',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0007','c299ad8c-012e-471c-8c0c-ac721fe242cf','PRATICHE','SELECT
    mese,
    anno,
    nvl(c, 0)
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(1) c,
            month_rif,
            year_rif
        FROM
            fm_flow_sdo_0
        WHERE
            month_rif IS NOT NULL
            AND year_rif IS NOT NULL
            and month_rif in (:mesi)
            and year_rif in (:anni)
        GROUP BY
            month_rif,
            year_rif
    ) a ON mese = month_rif
           AND anno = year_rif
           where mese in (:mesi)
and anno in (:anni)
ORDER BY
    to_number(anno),
    to_number(mese)','Pratiche',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,null,'75977a7c-253e-4249-97a6-a39384975222',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0021','c299ad8c-012e-471c-8c0c-ac721fe242cf','PRATICHE_RIC_REG','SELECT
    mese,
    anno,
    nvl(c, 0)
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(1) c,
            month_rif,
            year_rif
        FROM
            fm_flow_sdo_0
        WHERE
            month_rif IS NOT NULL
            AND year_rif IS NOT NULL
            AND state_send_region = ''ACCETTATA''
            AND status_region = ''VALIDO''
            and month_rif in (:mesi)
and year_rif in (:anni)
        GROUP BY
            month_rif,
            year_rif
    ) a ON mese = month_rif
           AND anno = year_rif
           where mese in (:mesi)
and anno in (:anni)
ORDER BY
    to_number(anno),
    to_number(mese)','Pratiche Riconosciute da Regione','card-header-success','grade','Visualizza pratiche riconosciute da regione','TRUE','REGIONALE','PRATICHE',null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'25756176-3508-4ab0-b6ee-d37634aea79f',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0030','4d971f52-0716-47bc-9255-5e9ca8f0d028','ERRORI_REG','SELECT
    mese,
    anno,
    nvl(c, 0)
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(1) c,
            month_rif,
            year_rif
        FROM
            fm_flow_emur_ps_0
            JOIN emur_ps_reg_scarti_regione ON emur_ps_reg_scarti_regione.codiceazienda = fm_flow_emur_ps_0.codiceazienda
                                             AND emur_ps_reg_scarti_regione.codicestruttura = fm_flow_emur_ps_0.codicestruttura
                                             AND
                                             fm_flow_emur_ps_0.codiceaccessops in (
                                                  select codiceaccessops
                                                  from fm_flow_emur_ps_reg_0 reg where
                                                    reg.kcodiceaccessops = emur_ps_reg_scarti_regione.kcodiceaccessops and
                                                    reg.CODICEAZIENDA = emur_ps_reg_scarti_regione.CODICEAZIENDA and
                                                    reg.codicestruttura = emur_ps_reg_scarti_regione.codicestruttura)
        WHERE
            month_rif IS NOT NULL
            AND year_rif IS NOT NULL
            AND month_rif IN (
                :mesi
            )
            AND year_rif IN (
                :anni
            )
        GROUP BY
            month_rif,
            year_rif
    ) a ON mese = month_rif
           AND anno = year_rif
WHERE
    mese IN (
        :mesi
    )
    AND anno IN (
        :anni
    )
ORDER BY
    to_number(anno),
    to_number(mese)','Errori Regionali','card-header-danger','error','Visualizza errori regionali','TRUE','REGIONALE','ERRORI',null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('05-FEB-20','DD-MON-RR'),'fbb42d01-1100-481c-8f99-3045aa58a4e8',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0016','4d971f52-0716-47bc-9255-5e9ca8f0d028','ERRORI_DISTINCT','SELECT
    mese,
    anno,
    SUM(nvl(mes, 0))
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(distinct b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_emur_ps_0 a
            LEFT JOIN fm_flow_emur_ps_0_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicestruttura = b.codicestruttura
                                                     AND a.codiceaccessops = b.codiceaccessops )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
AND B.SEVERITY = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(distinct b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_emur_ps_1 a
            LEFT JOIN fm_flow_emur_ps_1_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicestruttura = b.codicestruttura
                                                     AND a.codiceaccessops = b.codiceaccessops )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
AND B.SEVERITY = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(distinct b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_emur_ps_2 a
            LEFT JOIN fm_flow_emur_ps_2_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicestruttura = b.codicestruttura
                                                     AND a.codiceaccessops = b.codiceaccessops
                                                     AND b.progressivoprestazione = a.progressivoprestazione )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
AND B.SEVERITY = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(distinct b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_emur_ps_3 a
            LEFT JOIN fm_flow_emur_ps_3_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicestruttura = b.codicestruttura
                                                     AND a.codiceaccessops = b.codiceaccessops
                                                     AND b.progressivodiagnosi = a.progressivodiagnosi )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
AND B.SEVERITY = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
    ) q ON mese = month_rif
           AND anno = year_rif
           where mese in (:mesi)
and anno in (:anni)
GROUP BY
    mese,
    anno
ORDER BY
    to_number(anno),
    to_number(mese)','Errori Distinct',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,null,'f7c95857-174e-414d-9417-d0166da73272',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0009','c299ad8c-012e-471c-8c0c-ac721fe242cf','ERRORI_DISTINCT','SELECT
    mese,
    anno,
    SUM(nvl(mes, 0))
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(distinct b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_sdo_0 a
            LEFT JOIN fm_flow_sdo_0_message b ON ( a.codiceazienda = b.codiceazienda AND a.codicepresidio = b.codicepresidio AND a.progressivosdo = b.progressivosdo )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
AND B.SEVERITY = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(distinct b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_sdo_1 a
            LEFT JOIN fm_flow_sdo_1_message b ON ( a.codiceazienda = b.codiceazienda AND a.codicepresidio = b.codicepresidio AND a.progressivosdo = b.progressivosdo )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
AND B.SEVERITY = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(distinct b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_sdo_2 a
            LEFT JOIN fm_flow_sdo_2_message b ON ( a.codiceazienda = b.codiceazienda AND a.codicepresidio = b.codicepresidio AND a.progressivosdo = b.progressivosdo AND b.progressivodiagnosi = a.progressivodiagnosi )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
AND B.SEVERITY = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(distinct b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_sdo_3 a
            LEFT JOIN fm_flow_sdo_3_message b ON ( a.codiceazienda = b.codiceazienda AND a.codicepresidio = b.codicepresidio AND a.progressivosdo = b.progressivosdo AND b.progressivotrasferimento = a.progressivotrasferimento )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
AND B.SEVERITY = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
            UNION ALL
        SELECT
            COUNT(distinct b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_sdo_4 a
            LEFT JOIN fm_flow_sdo_4_message b ON ( a.codiceazienda = b.codiceazienda AND a.codicepresidio = b.codicepresidio AND a.progressivosdo = b.progressivosdo AND b.progressivointervento = a.progressivointervento )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
AND B.SEVERITY = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
    ) q ON mese = month_rif
           AND anno = year_rif
           where mese in (:mesi)
and anno in (:anni)
GROUP BY
    mese,
    anno
ORDER BY
    to_number(anno),
    to_number(mese)','Errori Distinct',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,null,'e048ce47-ec1b-4b84-b1c1-57742b71e4d3',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0015','4d971f52-0716-47bc-9255-5e9ca8f0d028','ERRORI','SELECT
    mese,
    anno,
    SUM(nvl(mes, 0))
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_emur_ps_0 a
            LEFT JOIN fm_flow_emur_ps_0_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicestruttura = b.codicestruttura
                                                     AND a.codiceaccessops = b.codiceaccessops )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            AND a.month_rif IN (
                :mesi
            )
            AND a.year_rif IN (
                :anni
            )
            AND b.severity = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_emur_ps_1 a
            LEFT JOIN fm_flow_emur_ps_1_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicestruttura = b.codicestruttura
                                                     AND a.codiceaccessops = b.codiceaccessops )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            AND a.month_rif IN (
                :mesi
            )
            AND a.year_rif IN (
                :anni
            )
            AND b.severity = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_emur_ps_2 a
            LEFT JOIN fm_flow_emur_ps_2_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicestruttura = b.codicestruttura
                                                     AND a.codiceaccessops = b.codiceaccessops
                                                     AND b.progressivoprestazione = a.progressivoprestazione )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            AND a.month_rif IN (
                :mesi
            )
            AND a.year_rif IN (
                :anni
            )
            AND b.severity = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_emur_ps_3 a
            LEFT JOIN fm_flow_emur_ps_3_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicestruttura = b.codicestruttura
                                                     AND a.codiceaccessops = b.codiceaccessops
                                                     AND b.progressivodiagnosi = a.progressivodiagnosi )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            AND a.month_rif IN (
                :mesi
            )
            AND a.year_rif IN (
                :anni
            )
            AND b.severity = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
    ) q ON mese = month_rif
           AND anno = year_rif
WHERE
    mese IN (
        :mesi
    )
    AND anno IN (
        :anni
    )
GROUP BY
    mese,
    anno
ORDER BY
    to_number(anno),
    to_number(mese)','Errori',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'fd001b86-5e85-4218-985e-1a4554f0f147',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into FM_TABGEN_VALUE (TABGEN_ID,FIELD1,FIELD2,FIELD3,FIELD4,FIELD5,FIELD6,FIELD7,FIELD8,FIELD9,FIELD10,FIELD11,FIELD12,FIELD13,FIELD14,FIELD15,FIELD16,FIELD17,FIELD18,FIELD19,FIELD20,DT_ENABLE,DT_DISABLE,ALWAYS_ENABLED,OPERATION_DATE,TV_ID,FIELD21,FIELD22,FIELD23,FIELD24,FIELD25,FIELD26,FIELD27,FIELD28,FIELD29,FIELD30,FIELD31,FIELD32,FIELD33,FIELD34,FIELD35,FIELD40,FIELD36,FIELD37,FIELD38,FIELD39) values ('FM_DASHBOARD_CONFIG','0008','c299ad8c-012e-471c-8c0c-ac721fe242cf','ERRORI','SELECT
    mese,
    anno,
    SUM(nvl(mes, 0))
FROM
    dashboardmeseanno left
    JOIN (
        SELECT
            COUNT(b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_sdo_0 a
            LEFT JOIN fm_flow_sdo_0_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicepresidio = b.codicepresidio
                                                     AND a.progressivosdo = b.progressivosdo )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
and b.severity = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_sdo_1 a
            LEFT JOIN fm_flow_sdo_1_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicepresidio = b.codicepresidio
                                                     AND a.progressivosdo = b.progressivosdo )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
and b.severity = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_sdo_2 a
            LEFT JOIN fm_flow_sdo_2_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicepresidio = b.codicepresidio
                                                     AND a.progressivosdo = b.progressivosdo
                                                     AND b.progressivodiagnosi = a.progressivodiagnosi )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
and b.severity = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
        UNION ALL
        SELECT
            COUNT(b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_sdo_3 a
            LEFT JOIN fm_flow_sdo_3_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicepresidio = b.codicepresidio
                                                     AND a.progressivosdo = b.progressivosdo
                                                     AND b.progressivotrasferimento = a.progressivotrasferimento )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
and b.severity = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
            UNION ALL
        SELECT
            COUNT(b.message) mes,
            a.month_rif,
            a.year_rif
        FROM
            fm_flow_sdo_4 a
            LEFT JOIN fm_flow_sdo_4_message b ON ( a.codiceazienda = b.codiceazienda
                                                     AND a.codicepresidio = b.codicepresidio
                                                     AND a.progressivosdo = b.progressivosdo
                                                     AND b.progressivointervento = a.progressivointervento )
        WHERE
            a.month_rif IS NOT NULL
            AND a.year_rif IS NOT NULL
            and a.month_rif in (:mesi)
and a.year_rif in (:anni)
and b.severity = ''ERROR''
        GROUP BY
            a.year_rif,
            a.month_rif
    ) q ON mese = month_rif
           AND anno = year_rif
           where mese in (:mesi)
and anno in (:anni)
GROUP BY
    mese,
    anno
ORDER BY
    to_number(anno),
    to_number(mese)','Errori',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01-JAN-00','DD-MON-RR'),to_date('01-JAN-00','DD-MON-RR'),null,to_date('17-FEB-20','DD-MON-RR'),'af7e8f67-7824-43ae-af51-e4ccbe808f31',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

