create table FM_VALIDATION_REQUEST_RESULT (
	VR_ID VARCHAR(64) PRIMARY KEY,
	IMPORTING_REQUEST_ID VARCHAR(64) UNIQUE,
	ERRORS INTEGER,
	WARNINGS INTEGER, 
	VALIDS INTEGER,
	VALIDATION_DATE TIMESTAMP
);